export default{
	list:[
		{
			title:'关于30岁的养生之道',
			subtit:'​食补养生是一种态度它只潜伏在聪明人',
			upusername:'张建军',
			uptime:'30分钟前',
			zan:'3056赞',
			pric:'https://ossweb-img.qq.com/images/lol/web201310/skin/big84000.jpg'
		},
		{
			title:'关于30岁的养生之道',
			subtit:'​食补养生是一种态度它只潜伏在聪明人',
			upusername:'张建军',
			uptime:'30分钟前',
			zan:'3056赞',
			pric:'https://ossweb-img.qq.com/images/lol/web201310/skin/big84000.jpg'
		},
		{
			title:'关于30岁的养生之道',
			subtit:'​食补养生是一种态度它只潜伏在聪明人',
			upusername:'张建军',
			uptime:'30分钟前',
			zan:'3056赞',
			pric:'https://ossweb-img.qq.com/images/lol/web201310/skin/big84000.jpg'
		},
		{
			title:'关于30岁的养生之道',
			subtit:'​食补养生是一种态度它只潜伏在聪明人',
			upusername:'张建军',
			uptime:'30分钟前',
			zan:'3056赞',
			pric:'https://ossweb-img.qq.com/images/lol/web201310/skin/big84000.jpg'
		},
		{
			title:'关于30岁的养生之道',
			subtit:'​食补养生是一种态度它只潜伏在聪明人',
			upusername:'张建军',
			uptime:'30分钟前',
			zan:'3056赞',
			pric:'https://ossweb-img.qq.com/images/lol/web201310/skin/big84000.jpg'
		},
		{
			title:'关于30岁的养生之道',
			subtit:'​食补养生是一种态度它只潜伏在聪明人',
			upusername:'张建军',
			uptime:'30分钟前',
			zan:'3056赞',
			pric:'https://ossweb-img.qq.com/images/lol/web201310/skin/big84000.jpg'
		},
		{
			title:'关于30岁的养生之道',
			subtit:'​食补养生是一种态度它只潜伏在聪明人',
			upusername:'张建军',
			uptime:'30分钟前',
			uptime:'3056赞',
			pric:'https://ossweb-img.qq.com/images/lol/web201310/skin/big84000.jpg'
		},
		{
			title:'关于30岁的养生之道',
			subtit:'​食补养生是一种态度它只潜伏在聪明人',
			upusername:'张建军',
			uptime:'30分钟前',
			uptime:'3056赞',
			pric:'https://ossweb-img.qq.com/images/lol/web201310/skin/big84000.jpg'
		}
	]
}